name: Build & Release APK

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode keystore file
        run: echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 -d > app/appynittyKeystore.jks

      - name: Give gradlew execute permission
        run: chmod +x ./gradlew
        working-directory: ${{ github.workspace }}

      - name: Build signed release APK
        run: ./gradlew assembleRelease -x lint
        working-directory: ${{ github.workspace }}

      - name: List APK output folder
        run: ls -lh app/build/outputs/apk/release/  # 🟢 Made more specific to show size & file presence

      - name: Rename APK to ZIP  # 🟢 NEW: Rename APK to avoid Gmail block
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/app-release.zip

      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.zip  # 🟢 update to zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Email Username
        run: |
          echo "Using email: ${{ secrets.GMAIL_USERNAME }}"

      - name: Send APK via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "New APK Build - NavigationCompose"
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: ${{ secrets.GMAIL_USERNAME }}
          body: |
            ✅ New APK build is ready.
            📎 APK is attached as a `.zip` file.
            🔧 Please rename `app-release.zip` to `app-release.apk` before installing.
          attachments: app/build/outputs/apk/release/app-release.zip  # 🟢 updated
