name: Build & Release APK

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode keystore file
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/appynittyKeystore.jks

      - name: Give gradlew execute permission
        run: chmod +x ./gradlew
        working-directory: ${{ github.workspace }}

      - name: Build signed release APK
        run: ./gradlew assembleRelease -x lint
        working-directory: ${{ github.workspace }}
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: List APK output folder
        run: ls -R app/build/outputs/apk/

      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release-unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send APK via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "New APK Build - NavigationCompose"
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: ${{ secrets.GMAIL_USERNAME }}
          body: "Download the attached APK."
          attachments: app/build/outputs/apk/release/app-release-unsigned.apk
